services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    environment:
      # Default creds:
      # - login: root
      # - password: rootpassword
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-rootpassword}
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db

  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"   # API Port (for apps/SDKs)
      - "127.0.0.1:9001:9001"   # Console Port (for Web UI)
    environment:
      RUSTFS_ACCESS_KEY: ${S3_ACCESS_KEY:-root}
      RUSTFS_SECRET_KEY: ${S3_SECRET_KEY:-rootpassword}
    volumes:
      - rustfs_data:/data
    command: server /data --console-address ":9001"

volumes:
  mongo_data:
    driver: local
  rustfs_data:
    driver: local
