services:
  bot:
    image: ghcr.io/aliakseych/dtmai:bot-latest
    restart: unless-stopped
    environment:
      # AI Stuff
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      # Telegram
      MONGO_URI: ${MONGO_URI}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      ADMINS_IDS: ${ADMINS_IDS}
      # MINIO
      MINIO_URL: ${MINIO_URL}
      MINIO_USERNAME: ${MINIO_USERNAME}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_PUBLIC_URL: ${MINIO_PUBLIC_URL}

  mongodb:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db

  minio:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    ports:
      - "0.0.0.0:9000:9000"     # API Port (for apps/SDKs)
      - "127.0.0.1:9001:9001"   # Console Port (for Web UI)
    environment:
      MINIO_ROOT_USER:  ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  mongo_data:
    driver: local
  minio_data:
    driver: local
